### PR TITLE
Don't add whitespace to replace newline. Use more stock styles.

### PR DESCRIPTION
**Pull request by wbinnssmith**
We were previously adding a single space to replace newlines, but since whitespace is now automatically fixed up according to the user's whitespace rules, we can skip this.

Also adhere more to esformatter's stock styles in tests.

### CODE REVIEW

**Comment by wbinnssmith** [comment]
cc @millermedeiros @kewah

**Comment by kewah** [comment]
Looks good to me :+1: 

I think it worth to mention in the readme the esformatter's settings we might need to change, in order to match our coding style. (ex: `whiteSpace.before.PropertyName`).

**Comment by millermedeiros** [comment]
:+1: about describing the options on the README and maybe even showing some examples like I did on the [esformatter-quotes](https://github.com/millermedeiros/esformatter-quotes/#examples)

**Comment by wbinnssmith** [comment]
Thanks guys. I agree that the readme needs a bit of work and could
certainly be clearer. Some folks have already forked this plugin to remove
things like max depth, when it should be easy to opt out of, and clear in
the readme now to do so.

Let me know if there's other things that should be in there.

**Pull request merged**
